[2025-04-10 21:22:22,963 INFO] [run_gptuner.py:<module>:99] Input arguments: Namespace(config='src/exp_configs/gpt-4o-overall.yml', db='postgres', database='tpcc_workload', test='tpcc', timeout=180, seed=100, result_path='./experiments_results/gpt-4o-overall_202504102122', model='gpt-4o', restart_cmd='sudo docker restart tpcc_workload', recover_script='./scripts/recover_docker_postgres.sh', user='postgres', password='postgres')
[2025-04-10 21:23:43,009 WARNING] [run_gptuner.py:<module>:146] 'checkpoint_segments' is not in postgres
[2025-04-11 11:38:35,666 INFO] [run_gptuner.py:<module>:104] Input arguments: Namespace(config='src/exp_configs/gpt-4o-overall.yml', folder='gpt-4o-overall_202504102122', process='optimization', db='postgres', database='postgres', test='tpcc', timeout=180, seed=100, result_path='./experiments_results/gpt-4o-overall_202504102122', model='gpt-4o', restart_cmd='sudo docker restart tpcc_workload', recover_script='./scripts/recover_docker_postgres.sh', user='postgres', password='postgres')
[2025-04-11 11:55:12,326 INFO] [run_gptuner.py:<module>:107] Input arguments: Namespace(config='src/exp_configs/gpt-4o-overall.yml', folder='gpt-4o-overall_202504102122', process='optimization', db='postgres', database='postgres', test='tpcc', timeout=180, seed=100, result_path='./experiments_results/gpt-4o-overall_202504102122', model='gpt-4o', restart_cmd='sudo docker restart tpcc_workload', recover_script='./scripts/recover_docker_postgres.sh', user='postgres', password='postgres')
[2025-04-11 11:56:43,987 INFO] [coarse_space.py:__init__:21] Coarse Configuration Space:
[2025-04-11 12:24:20,762 INFO] [fine_space.py:__init__:26] Fine Configuration Space:
