[2025-04-17 19:54:13,724 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '137';" to update dbms for error: 137 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 19:54:13,744 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '100';" to update dbms for error: 100 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-04-17 19:54:13,757 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 19:54:34,004 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-17 19:54:36,837 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 19:55:42,651 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '100';" to update dbms for error: 100 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-04-17 19:55:42,663 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 19:56:38,487 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 19:56:38,504 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '100';" to update dbms for error: 100 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-04-17 19:56:38,519 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 19:57:32,457 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 19:58:01,408 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 19:58:29,199 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '137';" to update dbms for error: 137 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 19:58:29,213 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '100';" to update dbms for error: 100 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-04-17 19:58:29,224 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 19:58:49,489 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-17 19:58:52,323 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 19:59:42,076 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 19:59:42,105 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:00:43,908 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '100';" to update dbms for error: 100 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-04-17 20:00:43,922 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:01:04,153 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-17 20:01:06,979 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:01:41,811 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '100';" to update dbms for error: 100 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-04-17 20:01:41,842 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:02:02,040 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-17 20:02:04,866 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '100';" to update dbms for error: 100 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-04-17 20:02:04,881 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:02:59,151 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '100';" to update dbms for error: 100 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-04-17 20:02:59,163 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:03:46,500 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 20:03:46,519 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '100';" to update dbms for error: 100 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-04-17 20:03:46,532 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:04:23,217 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '100';" to update dbms for error: 100 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-04-17 20:04:23,230 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:04:43,433 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-17 20:04:46,275 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:05:36,858 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:07:10,325 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 20:07:10,356 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:08:15,451 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '100';" to update dbms for error: 100 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-04-17 20:08:15,463 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:09:08,715 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:09:28,941 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-17 20:09:31,771 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:10:04,851 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '137';" to update dbms for error: 137 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 20:10:04,869 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '100';" to update dbms for error: 100 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-04-17 20:10:04,882 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:10:25,141 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-17 20:10:27,936 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 20:10:27,967 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:10:53,269 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 20:10:53,305 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:11:30,011 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 20:11:30,031 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '100';" to update dbms for error: 100 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-04-17 20:11:30,046 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:12:56,056 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '137';" to update dbms for error: 137 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 20:12:56,074 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '100';" to update dbms for error: 100 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-04-17 20:12:56,087 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:14:06,234 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '100';" to update dbms for error: 100 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-04-17 20:14:06,246 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:14:28,583 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-17 20:14:31,416 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:14:51,653 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-17 20:14:54,491 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '100';" to update dbms for error: 100 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-04-17 20:14:54,505 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:15:16,731 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-17 20:15:57,725 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 20:15:59,701 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:16:41,372 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:17:08,618 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:20:19,961 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:23:27,822 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:26:35,769 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:27:04,864 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 20:27:04,880 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '100';" to update dbms for error: 100 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-04-17 20:27:04,893 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:27:47,305 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:30:57,492 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:31:34,103 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 20:31:34,134 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:31:59,401 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 20:31:59,431 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:35:07,294 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:38:15,217 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:41:23,209 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:41:58,897 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:42:19,220 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-17 20:42:22,059 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:45:30,236 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:48:40,540 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:49:07,812 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:49:35,068 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 20:49:35,099 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:52:42,929 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 20:52:42,963 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:53:10,239 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:54:03,560 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:55:01,323 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:55:48,984 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:59:02,294 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 20:59:27,681 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:02:39,143 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 21:02:39,178 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:03:08,830 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 21:03:08,863 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:03:37,092 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 21:03:37,128 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:06:45,027 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:07:11,123 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 21:07:11,154 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:07:55,155 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:08:41,269 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:09:31,785 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:09:52,042 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-17 21:09:54,874 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 21:09:54,905 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:10:20,003 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 21:10:20,033 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:10:45,103 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 21:10:45,135 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:11:31,697 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 21:11:31,729 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:12:00,654 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:12:28,003 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:12:54,421 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:13:20,596 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:13:49,688 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:17:01,213 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:17:27,463 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 21:17:27,494 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:17:47,792 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-17 21:17:50,537 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:20:58,441 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:24:08,319 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:24:34,596 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:25:03,900 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 21:25:03,931 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:25:30,494 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:25:59,071 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:26:27,604 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:29:39,214 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 21:29:39,246 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:32:47,170 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:36:00,957 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 21:36:00,990 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:36:27,297 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 21:36:27,330 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:36:53,706 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 21:36:53,740 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:37:18,844 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 21:37:18,874 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:37:43,967 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:40:52,130 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:43:59,968 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:44:25,499 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:47:37,188 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:50:47,935 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:51:13,605 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:51:38,947 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:54:50,399 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 21:54:50,432 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:55:10,740 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-17 21:55:13,564 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:55:33,866 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-17 21:55:36,655 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 21:55:36,686 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:56:11,099 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 21:56:11,130 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:56:39,051 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 21:56:39,085 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:57:07,019 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '125';" to update dbms for error: 125 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-17 21:57:07,049 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:57:32,324 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 21:57:57,614 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 22:01:05,594 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 22:01:30,841 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 22:04:42,020 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-17 22:05:10,497 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

