[2025-04-10 21:17:56,908 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:17:57,006 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 21:19:27,401 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:19:27,457 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 21:19:47,647 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 21:20:11,307 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:21:45,658 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:21:45,719 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 21:22:05,896 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 21:22:29,476 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:22:29,534 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 21:22:29,566 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 21:22:49,700 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 21:23:13,204 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:23:13,263 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 21:23:13,297 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 21:23:40,928 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:24:01,202 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 21:24:24,926 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:24:25,203 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 21:26:00,373 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:26:00,468 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 21:26:20,650 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 21:26:44,292 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:26:44,351 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 21:27:04,549 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 21:27:28,933 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:29:01,359 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:29:01,451 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 21:30:32,045 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:32:06,857 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:33:46,961 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:33:47,022 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 21:33:47,057 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 21:34:07,263 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 21:34:30,746 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:34:30,799 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 21:34:51,027 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 21:35:14,657 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:35:14,720 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 21:35:14,757 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 21:35:34,943 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 21:35:58,590 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:35:58,660 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 21:36:18,817 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 21:36:42,466 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:36:42,563 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 21:38:18,984 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:39:53,689 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:40:14,031 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 21:40:37,812 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:42:11,237 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:42:11,295 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 21:42:31,515 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 21:42:55,144 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:43:15,660 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 21:43:39,200 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:43:59,508 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 21:44:23,153 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:44:43,454 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 21:45:07,011 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:45:07,064 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 21:45:27,356 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 21:45:50,993 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:45:51,083 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 21:46:13,363 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 21:46:36,909 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:46:37,005 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 21:46:57,175 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 21:47:20,760 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:47:43,162 ERROR] [postgres.py:update_dbms:117] Failed to execute "drop database if exists tpcc_template" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 21:47:43,162 ERROR] [postgres.py:update_dbms:117] Failed to execute "create database tpcc_template with template benchbase" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 21:47:43,162 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 21:49:36,870 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:49:36,962 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 21:51:17,187 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:51:17,282 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 21:53:00,709 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:54:40,335 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:54:40,436 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 21:56:11,250 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:56:11,347 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 21:57:46,049 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 21:58:06,321 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 21:58:29,900 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:00:04,426 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:00:04,519 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 22:01:41,752 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:02:02,004 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 22:02:25,688 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:02:45,977 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 22:03:09,530 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:03:29,875 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 22:03:53,448 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:03:53,539 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 22:05:24,581 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:05:24,684 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 22:06:59,233 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:08:39,881 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:09:00,191 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 22:09:23,777 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:09:23,840 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 22:09:44,134 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 22:10:07,607 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:10:07,705 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 22:10:29,988 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 22:10:53,692 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:12:24,686 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:12:24,779 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 22:13:56,103 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:13:56,200 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 22:15:30,805 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:15:51,134 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 22:16:14,951 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:16:35,256 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 22:16:58,807 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:16:58,874 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 22:17:19,092 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 22:17:42,724 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:17:42,818 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 22:19:17,274 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:19:17,327 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 22:19:39,434 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 22:20:02,909 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:20:03,006 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 22:21:43,895 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:21:43,953 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 22:21:43,988 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 22:23:23,730 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:23:23,841 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 22:24:58,403 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:24:58,496 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 22:26:39,092 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:26:39,184 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 22:28:19,638 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:28:19,733 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 22:30:00,066 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:31:36,506 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:31:36,599 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 22:33:16,095 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:34:50,816 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:34:50,914 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 22:36:27,472 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:36:27,568 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 22:38:06,488 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:39:42,000 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:39:42,090 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 22:41:16,404 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:41:16,491 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 22:42:55,908 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:42:56,018 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 22:44:33,125 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:46:07,597 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:47:42,944 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:49:17,426 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:49:17,479 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 22:49:37,721 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 22:50:01,326 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:51:35,498 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:53:10,352 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:54:49,620 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:54:49,673 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 22:55:12,141 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 22:55:35,656 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:55:35,760 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 22:57:15,344 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:58:47,259 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 22:58:47,347 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 23:00:21,569 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:00:41,906 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 23:01:05,593 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:01:05,685 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 23:02:39,886 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:02:39,952 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 23:03:00,052 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 23:03:23,908 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:05:03,692 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:05:26,489 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 23:05:50,127 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:05:50,216 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 23:07:24,320 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:07:24,415 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 23:08:59,487 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:10:34,008 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:10:34,111 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 23:12:09,017 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:12:09,072 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 23:12:09,108 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 23:12:29,309 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 23:12:52,953 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:13:13,289 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 23:13:36,979 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:13:37,073 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 23:15:11,830 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:15:11,979 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 23:15:32,344 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 23:15:55,875 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:15:55,965 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 23:16:18,601 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 23:16:42,048 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:17:02,389 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 23:17:26,083 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:17:26,142 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 23:19:00,832 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:19:00,893 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 23:19:00,927 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 23:20:34,754 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:22:10,452 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:22:30,823 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 23:22:54,430 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:23:14,798 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 23:23:38,316 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:23:38,378 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 23:25:16,648 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:26:51,843 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:27:12,190 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 23:27:35,801 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:27:35,858 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 23:29:10,617 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:29:10,720 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 23:29:31,027 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-10 23:29:54,680 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:29:54,770 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 23:31:30,087 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:31:30,140 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 23:31:30,171 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

[2025-04-10 23:33:14,253 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:34:49,718 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-10 23:34:49,780 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-10 23:34:49,814 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set max_locks_per_transaction to '0';" to update dbms for error: 0 is outside the valid range for parameter "max_locks_per_transaction" (10 .. 2147483647)

