[2025-05-18 03:34:23,130 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 03:34:23,132 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 03:34:23,818 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 03:34:23,819 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 03:37:30,062 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 03:37:30,064 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 03:37:30,182 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 03:37:30,183 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 03:37:30,241 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 03:37:30,243 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 03:37:30,270 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 03:37:30,271 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 03:37:30,281 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 03:37:30,282 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 03:37:30,310 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 03:37:30,311 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 03:40:51,924 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 03:40:51,926 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 03:40:52,026 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 03:40:52,027 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 03:40:52,110 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 03:40:52,111 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 03:40:52,254 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 03:40:52,255 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 03:40:52,271 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 03:40:52,271 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 03:41:13,245 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 03:42:47,109 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 03:42:47,111 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 03:42:47,210 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 03:42:47,211 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 03:42:47,298 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 03:42:47,298 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 03:42:47,381 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 03:42:47,382 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 03:42:47,452 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 03:42:47,453 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 03:42:47,495 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 03:42:47,496 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 03:42:47,498 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 03:42:47,498 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 03:46:14,965 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 03:46:14,967 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 03:46:15,058 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 03:46:15,059 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 03:46:15,173 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 03:46:15,175 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 03:46:15,466 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 03:46:15,467 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 03:49:51,479 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 03:49:51,481 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 03:49:51,601 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 03:49:51,602 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 03:49:51,914 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 03:49:51,915 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 03:53:37,286 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 03:53:37,288 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 03:53:37,852 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 03:53:37,853 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 03:53:37,899 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 03:53:37,900 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 03:53:59,656 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 03:56:09,151 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 03:56:09,152 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 03:56:09,221 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 03:56:09,222 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 03:56:09,278 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 03:56:09,278 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 03:56:09,341 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 03:56:09,342 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 03:56:09,387 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 03:56:09,388 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 03:56:09,415 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 03:56:09,416 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 03:59:43,922 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 03:59:43,923 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 03:59:43,976 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 03:59:43,977 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 03:59:44,030 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 03:59:44,031 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 03:59:44,058 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 03:59:44,059 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 03:59:44,114 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 03:59:44,115 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 04:03:15,838 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 04:03:15,839 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 04:03:15,956 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 04:03:15,957 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 04:03:16,041 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 04:03:16,042 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 04:03:16,095 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 04:03:16,096 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 04:03:36,544 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 04:05:36,510 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 04:05:36,511 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 04:09:00,888 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 04:09:00,889 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 04:09:00,939 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 04:09:00,940 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 04:09:00,983 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 04:09:00,984 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 04:09:01,011 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 04:09:01,012 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 04:12:26,860 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 04:12:26,862 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 04:12:26,918 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 04:12:26,919 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 04:12:26,947 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 04:12:26,948 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 04:12:26,958 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 04:12:26,958 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 04:12:26,987 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 04:12:26,988 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 04:12:26,989 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 04:12:26,989 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 04:12:47,405 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 04:14:43,927 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 04:14:43,928 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 04:14:44,054 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 04:14:44,055 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 04:14:44,108 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 04:14:44,109 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 04:14:44,137 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 04:14:44,137 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 04:14:44,147 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 04:14:44,147 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 04:14:44,189 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 04:14:44,190 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 04:15:04,559 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 04:16:42,801 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 04:16:42,803 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 04:16:42,905 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 04:16:42,906 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 04:16:42,940 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 04:16:42,941 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 04:19:54,018 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 04:19:54,019 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 04:19:54,140 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 04:19:54,141 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 04:19:54,198 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 04:19:54,199 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 04:19:54,227 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 04:19:54,228 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 04:19:54,237 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 04:19:54,238 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 04:19:54,267 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 04:19:54,268 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 04:20:14,722 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 04:22:09,849 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 04:22:09,850 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 04:22:09,944 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 04:22:09,945 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 04:22:09,954 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 04:22:09,955 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 04:22:09,991 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 04:22:09,992 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 04:22:30,446 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 04:24:18,977 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 04:24:18,978 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 04:24:19,071 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 04:24:19,072 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 04:24:19,082 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 04:24:19,083 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 04:27:42,983 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 04:27:42,984 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 04:27:43,097 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 04:27:43,098 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 04:27:43,127 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 04:27:43,128 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 04:31:18,461 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 04:31:18,462 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 04:31:18,648 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 04:31:18,650 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 04:31:19,061 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 04:31:19,062 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 04:31:19,267 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 04:31:19,268 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 04:31:40,247 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 04:33:21,235 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 04:33:21,237 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 04:33:21,299 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 04:33:21,299 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 04:33:21,385 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 04:33:21,386 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 04:36:04,882 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 04:36:04,884 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 04:36:04,938 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 04:36:04,939 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 04:36:05,052 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 04:36:05,053 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 04:36:05,099 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 04:36:05,099 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 04:39:08,250 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 04:39:08,251 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 04:39:08,303 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 04:39:08,304 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 04:39:08,392 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 04:39:08,392 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 04:39:08,402 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 04:39:08,403 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 04:42:26,624 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 04:42:26,626 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 04:42:26,843 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 04:42:26,844 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 04:45:39,740 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 04:45:39,741 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 04:45:39,854 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 04:45:39,854 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 04:45:39,883 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 04:45:39,884 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 04:46:00,375 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 04:47:46,680 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 04:47:46,681 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 04:47:46,744 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 04:47:46,745 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 04:47:46,798 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 04:47:46,799 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 04:47:46,883 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 04:47:46,884 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 04:47:46,893 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 04:47:46,893 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 04:47:46,918 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 04:47:46,919 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 04:48:07,384 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 04:49:59,791 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 04:49:59,792 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 04:49:59,918 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 04:49:59,919 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 04:49:59,976 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 04:49:59,977 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 04:50:00,060 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 04:50:00,061 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 04:50:00,062 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 04:50:00,062 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 04:53:16,341 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 04:53:16,342 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 04:53:16,461 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 04:53:16,462 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 04:53:16,514 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 04:53:16,515 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 04:53:16,541 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 04:53:16,542 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 04:53:16,552 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 04:53:16,552 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 04:53:16,579 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 04:53:16,580 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 04:53:38,767 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 04:55:43,201 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 04:55:43,203 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 04:55:43,356 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 04:55:43,357 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 04:55:43,444 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 04:55:43,445 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 04:55:43,492 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 04:55:43,493 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 04:55:43,561 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 04:55:43,562 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 04:56:04,184 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 04:58:05,229 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 04:58:05,230 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 04:58:05,321 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 04:58:05,322 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 04:58:27,815 ERROR] [postgres.py:update_dbms:117] Failed to execute "drop database if exists tpcc_template" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 04:58:27,815 ERROR] [postgres.py:update_dbms:117] Failed to execute "create database tpcc_template with template tpcc_workload" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 04:58:27,816 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 05:03:23,546 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 05:03:23,547 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 05:03:23,682 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 05:03:23,683 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 05:03:23,739 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 05:03:23,740 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 05:03:23,768 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 05:03:23,769 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 05:03:23,778 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 05:03:23,779 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 05:03:23,807 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 05:03:23,808 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 05:06:57,616 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 05:06:57,618 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 05:06:57,672 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 05:06:57,673 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 05:06:57,700 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 05:06:57,701 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 05:06:57,711 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 05:06:57,712 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 05:06:57,748 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 05:06:57,749 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 05:10:21,077 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 05:10:21,078 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 05:10:21,207 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 05:10:21,208 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 05:10:21,265 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 05:10:21,266 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 05:10:21,295 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 05:10:21,296 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 05:10:21,306 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 05:10:21,306 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 05:13:24,006 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 05:13:24,007 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 05:13:24,061 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 05:13:24,062 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 05:13:24,088 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 05:13:24,089 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 05:13:24,099 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 05:13:24,099 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 05:13:24,126 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 05:13:24,127 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 05:16:31,145 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 05:16:31,147 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 05:16:31,270 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 05:16:31,271 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 05:16:31,391 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 05:16:31,391 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 05:16:31,452 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 05:16:31,453 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 05:16:31,466 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 05:16:31,467 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 05:16:31,575 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 05:16:31,576 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 05:19:58,044 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 05:19:58,045 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 05:19:58,166 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 05:19:58,167 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 05:19:58,220 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 05:19:58,221 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 05:19:58,249 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 05:19:58,250 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 05:19:58,260 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 05:19:58,261 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 05:19:58,297 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 05:19:58,298 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 05:23:30,577 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 05:23:30,578 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 05:23:30,667 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 05:23:30,668 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 05:23:30,677 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 05:23:30,678 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 05:27:01,262 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 05:27:01,263 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 05:27:01,398 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 05:27:01,399 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 05:27:01,494 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 05:27:01,495 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 05:27:01,506 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 05:27:01,507 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 05:30:29,559 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 05:30:29,560 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 05:30:29,723 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 05:30:29,724 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 05:30:29,736 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 05:30:29,737 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 05:34:05,198 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 05:34:05,200 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 05:34:05,464 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 05:34:05,465 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 05:34:05,607 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 05:34:05,608 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 05:34:05,622 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 05:34:05,622 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 05:34:05,665 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 05:34:05,665 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 05:37:39,494 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 05:37:39,496 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 05:37:39,554 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 05:37:39,555 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 05:37:39,660 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 05:37:39,661 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 05:37:39,672 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 05:37:39,672 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 05:37:39,703 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 05:37:39,704 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 05:37:39,704 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 05:37:39,705 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 05:41:15,671 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 05:41:15,672 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 05:41:15,903 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 05:41:15,905 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 05:41:16,027 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 05:41:16,028 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 05:41:16,257 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 05:41:16,258 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 05:41:16,259 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 05:41:16,260 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 05:44:50,396 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 05:44:50,398 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 05:44:50,638 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 05:44:50,639 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 05:44:50,800 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 05:44:50,801 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 05:44:50,907 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 05:44:50,908 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 05:44:50,909 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 05:44:50,910 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 05:48:30,621 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 05:48:30,622 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 05:48:30,759 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 05:48:30,760 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 05:48:30,819 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 05:48:30,820 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 05:48:30,868 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 05:48:30,869 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 05:48:30,900 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 05:48:30,901 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 05:48:30,901 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 05:48:30,902 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 05:52:21,429 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 05:52:21,431 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 05:52:21,572 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 05:52:21,573 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 05:52:21,660 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 05:52:21,661 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 05:52:21,762 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 05:52:21,763 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 05:52:21,775 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 05:52:21,775 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 05:52:21,806 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 05:52:21,806 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 05:52:42,452 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 05:54:52,900 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 05:54:52,902 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 05:54:53,033 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 05:54:53,034 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 05:54:53,089 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 05:54:53,090 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 05:54:53,169 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 05:54:53,170 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 05:54:53,171 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 05:54:53,172 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 05:58:41,386 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 05:58:41,388 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 05:58:41,647 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 05:58:41,648 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 05:58:41,825 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 05:58:41,825 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 05:58:41,870 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 05:58:41,871 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 05:58:41,886 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 05:58:41,887 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 05:58:41,933 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 05:58:41,934 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 05:59:06,388 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 06:01:29,747 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 06:01:29,749 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 06:01:29,825 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 06:01:29,826 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 06:01:30,012 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 06:01:30,013 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 06:01:30,024 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 06:01:30,025 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 06:01:30,061 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 06:01:30,061 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 06:01:50,906 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 06:04:00,137 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 06:04:00,138 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 06:04:00,190 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 06:04:00,191 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 06:04:00,245 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 06:04:00,246 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 06:04:00,273 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 06:04:00,274 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 06:04:00,284 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 06:04:00,285 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 06:04:20,834 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 06:06:37,005 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 06:06:37,006 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 06:06:57,957 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 06:09:13,861 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 06:09:13,863 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 06:09:13,916 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 06:09:13,917 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 06:09:14,005 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 06:09:14,006 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 06:09:14,016 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 06:09:14,017 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 06:09:14,044 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 06:09:14,045 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 06:09:34,752 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 06:11:43,091 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 06:11:43,093 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 06:11:43,157 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 06:11:43,158 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 06:11:43,562 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 06:11:43,563 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 06:11:43,564 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 06:11:43,566 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 06:12:04,288 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 06:14:27,306 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 06:14:27,307 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 06:14:27,441 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 06:14:27,442 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 06:14:48,513 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 06:17:22,619 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 06:17:22,620 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 06:17:22,863 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 06:17:22,864 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 06:17:22,916 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 06:17:22,917 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 06:17:47,241 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 06:20:26,802 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 06:20:26,803 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 06:20:27,054 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 06:20:27,055 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 06:20:27,217 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 06:20:27,218 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 06:20:27,231 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 06:20:27,231 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 06:20:27,275 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 06:20:27,276 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 06:20:50,759 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 06:23:25,655 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 06:23:25,657 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 06:23:26,518 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 06:23:26,519 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 06:23:26,602 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 06:23:26,603 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 06:27:30,965 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 06:27:30,967 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 06:27:31,037 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 06:27:31,038 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 06:27:31,096 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 06:27:31,097 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 06:27:31,154 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 06:27:31,155 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 06:27:31,239 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 06:27:31,239 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 06:27:31,240 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 06:27:31,241 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 06:31:33,502 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 06:31:33,503 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 06:31:33,556 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 06:31:33,557 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 06:31:33,646 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 06:31:33,647 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 06:31:33,693 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 06:31:33,694 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 06:34:32,194 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 06:34:32,196 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 06:34:32,250 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 06:34:32,250 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 06:34:32,339 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 06:34:32,340 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 06:37:48,400 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 06:37:48,401 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 06:37:48,522 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 06:37:48,523 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 06:37:48,576 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 06:37:48,576 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 06:37:48,602 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 06:37:48,602 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 06:37:48,645 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 06:37:48,646 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 06:41:08,098 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 06:41:08,099 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 06:41:08,154 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 06:41:08,154 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 06:41:08,208 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 06:41:08,209 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 06:41:08,290 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 06:41:08,290 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 06:44:24,262 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 06:44:24,263 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 06:44:24,369 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 06:44:24,370 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 06:47:45,297 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 06:47:45,299 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 06:47:45,357 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 06:47:45,358 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 06:47:45,387 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 06:47:45,388 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 06:47:45,398 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 06:47:45,398 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 06:47:45,425 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 06:47:45,426 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 06:51:20,857 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 06:51:20,858 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 06:51:20,916 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 06:51:20,917 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 06:51:20,945 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 06:51:20,946 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 06:51:20,957 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 06:51:20,957 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 06:51:20,985 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 06:51:20,986 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 06:54:57,073 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 06:54:57,075 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 06:54:57,125 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 06:54:57,126 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 06:54:57,181 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 06:54:57,182 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 06:54:57,209 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 06:54:57,210 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 06:54:57,219 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 06:54:57,220 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 06:54:57,254 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 06:54:57,255 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 06:58:33,596 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 06:58:33,597 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 06:58:33,686 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 06:58:33,687 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 06:58:33,733 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 06:58:33,734 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 07:01:30,633 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 07:01:30,634 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 07:01:30,726 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 07:01:30,727 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 07:01:30,737 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 07:01:30,738 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 07:04:36,109 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 07:04:36,111 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 07:04:36,204 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 07:04:36,205 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 07:04:36,258 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 07:04:36,259 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 07:08:03,158 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 07:08:03,160 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 07:08:03,322 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 07:08:03,323 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 07:11:58,607 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 07:11:58,608 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 07:11:58,813 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 07:11:58,814 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 07:11:59,086 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 07:11:59,087 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 07:11:59,131 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 07:11:59,132 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 07:15:56,662 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 07:15:56,663 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 07:15:56,826 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 07:15:56,827 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 07:15:56,844 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 07:15:56,845 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 07:19:59,730 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 07:19:59,731 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 07:19:59,862 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 07:19:59,862 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 07:19:59,959 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 07:19:59,960 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 07:19:59,972 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 07:19:59,973 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 07:23:53,841 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 07:23:53,842 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 07:23:54,041 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 07:23:54,042 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 07:23:54,084 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 07:23:54,085 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 07:23:54,120 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 07:23:54,120 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 07:23:54,121 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 07:23:54,122 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 07:27:47,026 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 07:27:47,028 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 07:27:47,298 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 07:27:47,299 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 07:27:47,566 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 07:27:47,567 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 07:27:47,826 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 07:27:47,827 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 07:27:48,185 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 07:27:48,186 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 07:27:48,187 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 07:27:48,188 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 07:28:12,228 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 07:30:57,152 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 07:30:57,153 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 07:30:57,282 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 07:30:57,283 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 07:30:57,515 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 07:30:57,516 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 07:30:57,528 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 07:30:57,529 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 07:30:57,561 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 07:30:57,562 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 07:34:44,953 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 07:34:44,955 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 07:34:45,018 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 07:34:45,019 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 07:34:45,123 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 07:34:45,123 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 07:34:45,136 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 07:34:45,137 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 07:38:19,747 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 07:38:19,748 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 07:38:19,799 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 07:38:19,799 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 07:38:19,885 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 07:38:19,886 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 07:42:05,845 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 07:42:05,847 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 07:42:05,914 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 07:42:05,915 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 07:42:05,973 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 07:42:05,974 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 07:42:06,035 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 07:42:06,036 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 07:42:06,065 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 07:42:06,066 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 07:42:06,077 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 07:42:06,078 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 07:45:57,476 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 07:45:57,477 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 07:45:57,537 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 07:45:57,538 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 07:45:57,632 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 07:45:57,633 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 07:49:51,375 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 07:49:51,377 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 07:49:51,538 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 07:49:51,539 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 07:49:51,655 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 07:49:51,656 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 07:53:26,165 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 07:53:26,167 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 07:53:26,321 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 07:53:26,323 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 07:53:26,519 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 07:53:26,520 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 07:57:15,487 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 07:57:15,488 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 07:57:15,542 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 07:57:15,543 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 07:57:15,635 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 07:57:15,636 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 08:00:58,780 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 08:00:58,782 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 08:00:58,908 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 08:00:58,909 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 08:00:58,965 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 08:00:58,965 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 08:00:58,995 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 08:00:58,996 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 08:00:59,005 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 08:00:59,006 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 08:04:39,393 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 08:04:39,395 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 08:04:39,551 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 08:04:39,552 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 08:04:39,814 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 08:04:39,815 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 08:04:39,929 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 08:04:39,930 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 08:04:39,932 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 08:04:39,933 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 08:05:00,482 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 08:07:17,044 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 08:07:17,046 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 08:07:17,197 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 08:07:17,199 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 08:07:17,320 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 08:07:17,320 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 08:07:17,442 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 08:07:17,443 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 08:07:17,509 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 08:07:17,510 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 08:10:49,963 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 08:10:49,964 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 08:10:50,072 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 08:10:50,073 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 08:10:50,108 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 08:10:50,109 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 08:11:12,998 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 08:13:17,066 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 08:13:17,067 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 08:13:17,119 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 08:13:17,120 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 08:13:17,163 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 08:13:17,164 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 08:13:17,190 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 08:13:17,191 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 08:16:40,513 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 08:16:40,514 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 08:16:40,633 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 08:16:40,634 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 08:16:40,737 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 08:16:40,738 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 08:16:40,771 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 08:16:40,772 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 08:20:09,306 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 08:20:09,307 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 08:20:09,360 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 08:20:09,360 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 08:20:09,404 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 08:20:09,405 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 08:20:09,440 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 08:20:09,440 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 08:23:41,652 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 08:23:41,653 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 08:23:41,711 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 08:23:41,712 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 08:23:41,760 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 08:23:41,761 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 08:27:22,494 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 08:27:22,496 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 08:27:22,664 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 08:27:22,664 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 08:27:22,773 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 08:27:22,773 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 08:27:22,885 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 08:27:22,886 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 08:27:22,927 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 08:27:22,928 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 08:27:43,569 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 08:30:04,952 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 08:30:04,954 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 08:30:05,316 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 08:30:05,317 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 08:30:05,578 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 08:30:05,579 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 08:30:05,591 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 08:30:05,592 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 08:30:05,697 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 08:30:05,698 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 08:33:34,905 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 08:33:34,907 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 08:33:35,071 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 08:33:35,072 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 08:33:35,165 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 08:33:35,166 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 08:33:35,177 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 08:33:35,178 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 08:37:33,993 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 08:37:33,994 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 08:37:34,104 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 08:37:34,105 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 08:37:34,132 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 08:37:34,132 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 08:37:54,772 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 08:39:59,680 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 08:39:59,681 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 08:39:59,795 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 08:39:59,795 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 08:39:59,846 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 08:39:59,847 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 08:39:59,872 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 08:39:59,872 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 08:39:59,922 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 08:39:59,923 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 08:40:23,222 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 08:42:24,822 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 08:42:24,823 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 08:42:24,877 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 08:42:24,878 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 08:42:25,015 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 08:42:25,016 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 08:42:25,017 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 08:42:25,017 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 08:45:36,897 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 08:45:36,899 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 08:45:36,952 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 08:45:36,953 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 08:48:52,015 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 08:48:52,016 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 08:48:52,095 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 08:48:52,095 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 08:48:52,173 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 08:48:52,174 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 08:48:52,237 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 08:48:52,238 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 08:48:52,278 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 08:48:52,278 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 08:52:23,055 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 08:52:23,056 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 08:52:23,160 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 08:52:23,161 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 08:52:23,187 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 08:52:23,188 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 08:55:48,639 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 08:55:48,640 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 08:55:48,698 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 08:55:48,699 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 08:55:48,750 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 08:55:48,750 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 08:55:48,890 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 08:55:48,890 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 08:59:14,707 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 08:59:14,708 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 08:59:14,771 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 08:59:14,772 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 08:59:14,826 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 08:59:14,827 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 08:59:14,935 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 08:59:14,936 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 08:59:14,963 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 08:59:14,964 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 09:02:37,698 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 09:02:37,700 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 09:02:37,752 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 09:02:37,753 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 09:02:37,806 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 09:02:37,806 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 09:02:37,849 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 09:02:37,850 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 09:02:37,884 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 09:02:37,885 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 09:06:08,503 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 09:06:08,504 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 09:06:08,672 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 09:06:08,673 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 09:06:08,828 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 09:06:08,829 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 09:06:09,093 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 09:06:09,094 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 09:06:09,136 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 09:06:09,137 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 09:06:09,199 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 09:06:09,200 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 09:09:35,393 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 09:09:35,394 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 09:09:35,503 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 09:09:35,504 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 09:09:35,531 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 09:09:35,532 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 09:12:53,143 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 09:12:53,144 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 09:12:53,233 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 09:12:53,234 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 09:12:53,244 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 09:12:53,244 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 09:12:53,271 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 09:12:53,272 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 09:12:53,273 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 09:12:53,273 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 09:16:12,531 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 09:16:12,533 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 09:16:12,658 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 09:16:12,659 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 09:16:12,713 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 09:16:12,714 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 09:16:12,742 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 09:16:12,742 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 09:16:12,753 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 09:16:12,753 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 09:16:12,789 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 09:16:12,790 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 09:16:33,306 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 09:18:24,516 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 09:18:24,517 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 09:18:24,614 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 09:18:24,615 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 09:18:24,750 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 09:18:24,751 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 09:21:46,524 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 09:21:46,526 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 09:21:46,640 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 09:21:46,640 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 09:21:46,692 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_vacuum_threshold to '-1';" to update dbms for error: -1 is outside the valid range for parameter "autovacuum_vacuum_threshold" (0 .. 2147483647)

[2025-05-18 09:21:46,693 INFO] [postgres.py:set_knob:130] Knob autovacuum_vacuum_threshold is set to 50
[2025-05-18 09:21:46,720 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-05-18 09:21:46,721 INFO] [postgres.py:set_knob:130] Knob autovacuum_multixact_freeze_max_age is set to 400000000
[2025-05-18 09:21:46,730 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 09:21:46,730 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 09:21:46,755 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 09:21:46,755 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 09:21:46,756 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 09:21:46,756 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 09:22:07,297 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-18 09:24:07,215 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 09:24:07,217 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 09:24:07,384 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set vacuum_cost_limit to '-1';" to update dbms for error: -1 is outside the valid range for parameter "vacuum_cost_limit" (1 .. 10000)

[2025-05-18 09:24:07,385 INFO] [postgres.py:set_knob:130] Knob vacuum_cost_limit is set to 200
[2025-05-18 09:24:07,518 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 09:24:07,519 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-18 09:24:07,693 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set checkpoint_timeout to '0';" to update dbms for error: 0 s is outside the valid range for parameter "checkpoint_timeout" (30 .. 86400)

[2025-05-18 09:24:07,694 INFO] [postgres.py:set_knob:130] Knob checkpoint_timeout is set to 5min
[2025-05-18 09:24:07,722 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_freeze_max_age" (100000 .. 2000000000)

[2025-05-18 09:24:07,723 INFO] [postgres.py:set_knob:130] Knob autovacuum_freeze_max_age is set to 200000000
[2025-05-18 09:24:07,724 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set bgwriter_lru_maxpages to '-1';" to update dbms for error: -1 is outside the valid range for parameter "bgwriter_lru_maxpages" (0 .. 1073741823)

[2025-05-18 09:24:07,724 INFO] [postgres.py:set_knob:130] Knob bgwriter_lru_maxpages is set to 100
[2025-05-18 09:27:24,811 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-18 09:27:24,812 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-18 09:27:25,168 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-18 09:27:25,169 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
