[2025-04-13 16:05:34,633 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:05:34,667 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:05:34,668 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:07:09,590 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 16:07:09,673 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:07:09,712 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:07:09,713 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:08:41,557 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:08:41,591 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:08:41,592 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:10:12,625 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 16:10:12,708 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:10:12,743 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:10:12,743 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:11:44,760 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:11:44,793 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:11:44,793 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:13:15,973 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 16:13:16,053 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:13:16,086 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:13:16,087 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:14:47,507 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 16:14:47,590 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:14:47,626 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:14:47,627 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:16:18,892 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 16:16:18,967 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:16:18,998 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:16:18,999 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:16:39,158 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-13 16:17:02,844 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:17:02,884 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:17:02,885 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:17:23,124 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-13 16:17:47,019 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:17:47,051 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:17:47,051 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:19:22,612 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:19:22,648 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:19:22,649 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:20:55,080 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:20:55,118 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:20:55,119 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:22:26,471 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:22:26,505 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:22:26,506 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:22:46,676 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-13 16:23:10,548 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:23:10,581 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:23:10,582 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:24:41,981 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:24:42,014 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:24:42,015 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:25:02,216 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-13 16:25:26,181 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:25:26,218 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:25:26,219 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:25:46,425 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-13 16:26:10,459 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:26:10,489 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:26:10,489 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:27:44,517 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:27:44,550 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:27:44,551 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:28:04,774 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-13 16:28:28,564 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:28:28,597 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:28:28,598 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:30:04,877 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 16:30:04,960 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:30:04,996 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:30:04,996 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:30:25,240 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-13 16:30:49,009 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 16:30:49,092 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:30:49,127 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:30:49,128 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:31:09,342 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-13 16:31:33,367 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:31:33,400 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:31:33,401 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:31:53,551 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-13 16:32:17,551 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 16:32:17,632 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:32:17,668 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:32:17,669 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:32:37,879 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-13 16:33:01,722 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:33:01,758 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:33:01,759 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:33:21,983 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-13 16:33:45,773 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 16:33:45,859 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:33:45,893 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:33:45,894 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:34:06,133 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-13 16:34:30,175 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:34:30,207 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:34:30,208 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:36:04,436 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:36:04,472 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:36:04,473 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:37:35,492 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:37:35,527 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:37:35,528 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:39:08,347 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:39:08,382 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:39:08,383 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:40:39,474 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:40:39,506 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:40:39,507 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:43:45,738 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:43:45,770 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:43:45,771 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:45:29,104 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:45:29,137 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:45:29,138 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:47:09,993 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 16:47:10,070 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:47:10,103 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:47:10,104 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:48:41,796 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 16:48:41,881 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:48:41,914 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:48:41,915 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:50:24,011 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:50:24,047 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:50:24,048 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:52:05,553 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 16:52:05,624 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:52:05,656 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:52:05,657 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:53:52,869 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 16:53:52,943 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:53:52,977 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:53:52,978 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:55:34,597 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 16:55:34,679 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:55:34,711 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:55:34,711 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:57:12,083 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:57:12,120 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:57:12,121 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 16:58:43,514 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 16:58:43,550 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 16:58:43,551 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:00:18,599 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:00:18,631 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:00:18,632 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:01:56,565 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 17:01:56,647 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:01:56,682 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:01:56,682 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:03:28,581 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:03:28,616 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:03:28,616 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:05:10,671 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 17:05:10,745 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:05:10,779 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:05:10,780 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:06:51,899 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:06:51,931 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:06:51,932 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:07:12,146 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-13 17:07:35,998 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:07:36,030 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:07:36,031 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:09:12,735 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 17:09:12,806 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:09:12,838 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:09:12,839 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:09:35,764 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-13 17:09:59,818 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:09:59,851 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:09:59,851 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:11:35,085 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:11:35,117 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:11:35,118 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:13:06,309 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:13:06,345 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:13:06,346 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:14:44,289 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:14:44,326 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:14:44,326 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:16:19,425 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:16:19,459 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:16:19,459 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:17:54,525 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:17:54,557 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:17:54,557 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:19:29,169 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:19:29,205 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:19:29,206 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:21:05,793 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 17:21:05,873 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:21:05,905 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:21:05,906 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:23:02,726 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 17:23:02,801 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:23:02,833 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:23:02,834 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:24:35,217 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:24:35,252 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:24:35,252 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:24:55,471 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-13 17:25:19,562 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 17:25:19,638 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:25:19,671 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:25:19,672 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:26:51,143 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 17:26:51,225 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:26:51,260 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:26:51,261 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:28:27,280 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 17:28:27,512 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:28:27,616 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:28:27,617 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:29:59,591 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 17:29:59,676 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:29:59,713 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:29:59,715 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:31:31,442 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 17:31:31,677 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:31:31,782 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:31:31,783 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:33:09,739 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:33:09,776 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:33:09,776 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:34:44,710 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:34:44,744 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:34:44,745 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:36:16,470 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 17:36:16,544 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:36:16,577 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:36:16,578 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:37:56,360 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:37:56,392 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:37:56,393 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:39:30,289 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:39:30,324 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:39:30,325 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:41:05,098 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:41:05,132 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:41:05,133 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:42:36,650 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:42:36,684 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:42:36,684 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:44:08,615 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:44:08,649 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:44:08,650 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:45:42,534 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:45:42,570 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:45:42,571 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:47:17,355 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:47:17,390 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:47:17,390 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:48:52,832 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:48:52,869 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:48:52,869 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:50:37,849 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:50:37,882 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:50:37,883 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:50:58,132 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-13 17:51:21,966 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:51:22,006 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:51:22,007 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:53:00,532 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:53:00,566 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:53:00,566 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:54:39,990 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:54:40,095 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:54:40,096 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:56:11,962 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:56:11,996 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:56:11,997 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:57:49,619 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:57:49,650 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:57:49,651 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 17:59:24,185 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 17:59:24,218 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 17:59:24,218 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:01:03,059 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:01:03,096 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:01:03,097 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:02:41,125 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:02:41,157 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:02:41,158 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:04:16,535 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:04:16,571 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:04:16,572 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:05:52,041 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:05:52,079 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:05:52,080 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:07:29,261 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:07:29,296 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:07:29,296 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:09:07,343 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:09:07,377 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:09:07,378 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:10:48,853 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:10:48,887 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:10:48,888 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:12:24,303 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:12:24,338 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:12:24,338 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:13:59,070 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 18:13:59,147 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:13:59,180 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:13:59,181 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:15:31,043 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 18:15:31,118 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:15:31,150 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:15:31,151 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:17:02,929 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:17:02,965 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:17:02,966 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:17:23,268 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-13 18:17:47,205 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:17:47,237 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:17:47,238 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:18:07,499 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-13 18:18:31,437 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:18:31,473 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:18:31,475 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:20:03,846 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 18:20:03,926 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:20:03,961 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:20:03,962 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:20:24,249 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-13 18:20:48,296 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:20:48,332 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:20:48,332 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:22:21,949 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:22:21,985 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:22:21,986 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:23:56,863 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:23:56,902 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:23:56,903 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:25:29,029 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:25:29,063 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:25:29,064 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:25:49,257 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-13 18:26:13,343 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:26:13,377 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:26:13,378 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:27:48,139 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 18:27:48,224 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:27:48,256 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:27:48,257 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:28:08,522 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-13 18:28:32,271 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 18:28:32,350 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:28:32,384 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:28:32,384 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:30:04,501 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:30:04,536 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:30:04,537 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:31:43,330 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:31:43,366 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:31:43,367 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:32:03,659 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-13 18:32:27,623 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:32:27,656 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:32:27,657 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:34:05,702 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:34:05,738 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:34:05,739 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:35:38,002 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:35:38,040 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:35:38,041 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:35:58,315 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-13 18:36:22,183 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:36:22,220 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:36:22,220 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:38:00,623 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 18:38:00,704 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:38:00,742 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:38:00,743 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:39:48,995 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:39:49,027 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:39:49,028 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-13 18:41:27,162 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-13 18:41:27,235 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-13 18:41:27,266 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_block_size to '8192';" to update dbms for error: parameter "wal_block_size" cannot be changed

[2025-04-13 18:41:27,267 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

