[2025-05-23 17:14:52,590 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 17:14:52,592 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 17:14:52,594 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:14:52,594 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:15:13,009 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:15:40,616 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 17:15:40,618 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 17:15:40,619 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:15:40,619 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:15:40,682 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 17:15:40,682 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 17:16:00,897 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:16:26,439 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:16:26,440 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:16:46,787 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:17:12,092 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:17:12,093 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:17:12,154 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 17:17:12,155 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 17:17:32,412 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:17:57,771 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 17:17:57,772 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 17:17:57,773 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:17:57,774 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:18:18,131 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:18:43,553 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:18:43,554 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:18:43,609 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 17:18:43,610 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 17:19:03,888 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:19:29,341 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 17:19:29,343 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 17:19:29,344 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:19:29,345 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:19:49,694 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:20:15,166 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:20:15,167 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:21:58,040 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:21:58,042 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:21:58,099 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 17:21:58,099 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 17:22:18,414 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:22:43,682 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 17:22:43,683 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 17:22:43,685 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:22:43,686 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:22:43,741 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 17:22:43,741 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 17:23:04,027 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:23:29,654 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:23:29,656 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:25:03,277 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 17:25:03,278 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 17:25:03,280 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:25:03,281 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:25:23,607 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:25:48,974 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 17:25:48,975 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 17:25:48,977 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:25:48,978 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:25:49,048 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 17:25:49,048 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 17:26:09,368 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:26:34,952 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:26:34,954 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:26:35,027 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 17:26:35,028 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 17:26:55,268 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:27:20,651 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:27:20,652 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:27:41,003 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:28:06,423 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:28:06,424 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:28:06,499 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 17:28:06,500 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 17:29:38,723 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:29:38,725 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:29:38,786 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 17:29:38,787 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 17:29:59,053 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:30:24,300 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:30:24,302 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:30:44,651 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:31:10,170 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:31:10,171 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:31:32,269 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:31:57,619 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:31:57,620 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:33:34,392 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:33:34,393 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:33:34,462 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 17:33:34,463 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 17:33:54,727 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:34:20,182 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:34:20,183 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:34:20,239 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 17:34:20,239 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 17:34:40,534 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:35:05,835 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:35:05,837 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:35:26,190 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:35:51,575 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 17:35:51,577 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 17:35:51,579 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:35:51,580 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:35:51,645 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 17:35:51,646 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 17:36:11,966 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:36:37,213 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 17:36:37,215 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 17:36:37,216 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:36:37,217 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:38:09,984 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 17:38:09,986 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 17:38:09,988 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:38:09,988 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:38:10,059 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 17:38:10,060 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 17:38:30,319 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:38:55,483 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:38:55,485 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:38:55,542 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 17:38:55,543 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 17:39:15,901 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:39:41,063 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:39:41,064 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:39:41,126 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 17:39:41,127 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 17:42:02,154 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:42:02,155 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:42:02,215 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 17:42:02,216 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 17:42:22,568 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:42:51,074 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:42:51,076 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:42:51,131 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 17:42:51,132 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 17:43:13,415 ERROR] [postgres.py:update_dbms:117] Failed to execute "drop database if exists tpcc_template" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:43:13,415 ERROR] [postgres.py:update_dbms:117] Failed to execute "create database tpcc_template with template tpcc_workload" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:43:13,415 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:45:13,407 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:45:13,409 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:46:45,872 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:46:45,873 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:48:34,725 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:48:34,726 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:48:55,089 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:49:20,805 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:49:20,807 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:49:41,231 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:50:06,643 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:50:06,644 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:50:27,004 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:50:52,442 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:50:52,443 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:51:12,769 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:51:38,171 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:51:38,173 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:51:58,534 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:52:23,849 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:52:23,850 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:52:46,808 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:53:12,430 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:53:12,431 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:53:32,790 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:53:58,179 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:53:58,180 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:55:31,229 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:55:31,230 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:57:03,552 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 17:57:03,554 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 17:57:03,555 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:57:03,555 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:57:23,941 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:57:49,450 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:57:49,451 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 17:57:49,514 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 17:57:49,514 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 17:58:09,802 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 17:58:35,266 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 17:58:35,268 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:00:07,779 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 18:00:07,780 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 18:00:07,782 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:00:07,783 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:00:07,846 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 18:00:07,846 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 18:00:28,185 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 18:00:53,576 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:00:53,578 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:00:53,633 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 18:00:53,633 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 18:01:13,991 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 18:01:39,482 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:01:39,482 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:01:39,540 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 18:01:39,540 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 18:02:02,436 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 18:02:27,640 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:02:27,641 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:04:00,342 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:04:00,343 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:04:00,405 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 18:04:00,406 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 18:04:20,743 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 18:04:46,044 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:04:46,045 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:06:18,348 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:06:18,349 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:06:18,408 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 18:06:18,409 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 18:08:25,590 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:08:25,592 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:10:06,630 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:10:06,632 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:10:06,690 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 18:10:06,690 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 18:11:53,413 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 18:11:53,414 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 18:11:53,416 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:11:53,417 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:13:26,933 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:13:26,934 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:13:26,995 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 18:13:26,996 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 18:13:49,947 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 18:14:15,275 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:14:15,276 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:15:47,733 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 18:15:47,734 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 18:15:47,736 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:15:47,736 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:15:47,799 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 18:15:47,799 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 18:16:08,133 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 18:16:33,449 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:16:33,450 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:16:33,510 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 18:16:33,511 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 18:16:53,831 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 18:17:19,307 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:17:19,309 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:18:52,360 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:18:52,362 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:20:39,983 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 18:20:39,985 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 18:20:39,986 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:20:39,987 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:20:40,106 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 18:20:40,107 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 18:22:12,934 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:22:12,936 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:23:56,239 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:23:56,241 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:25:36,874 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:25:36,876 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:27:08,917 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 18:27:08,919 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 18:27:08,921 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:27:08,922 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:27:09,004 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 18:27:09,005 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 18:27:29,350 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 18:27:54,639 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 18:27:54,641 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 18:27:54,642 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:27:54,643 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:29:27,369 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 18:29:27,371 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 18:29:27,372 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:29:27,373 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:30:59,610 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:30:59,611 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:32:31,747 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:32:31,749 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:34:11,680 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 18:34:11,682 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 18:34:11,683 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:34:11,684 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:35:46,599 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:35:46,600 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:36:06,995 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 18:36:32,325 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:36:32,326 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:36:52,736 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 18:37:18,164 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:37:18,165 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:37:38,644 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 18:38:04,007 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:38:04,009 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:38:04,076 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 18:38:04,077 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 18:38:24,425 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 18:38:49,762 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:38:49,764 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:40:30,809 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:40:30,810 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:42:11,961 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:42:11,963 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:42:32,375 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 18:42:57,799 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:42:57,800 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:42:57,866 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 18:42:57,867 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 18:43:20,942 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 18:43:46,478 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:43:46,480 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:45:18,671 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:45:18,673 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:46:52,261 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 18:46:52,263 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 18:46:52,264 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:46:52,264 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:48:31,016 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 18:48:31,017 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 18:48:31,019 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:48:31,020 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:48:31,152 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 18:48:31,153 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 18:50:03,924 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:50:03,925 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:51:36,217 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 18:51:36,218 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 18:51:36,219 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:51:36,220 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:51:36,286 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 18:51:36,287 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 18:51:56,661 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 18:52:22,193 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:52:22,194 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:53:55,428 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 18:53:55,429 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 18:53:55,430 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:53:55,431 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:54:18,732 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 18:54:45,217 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:54:45,218 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:56:18,941 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:56:18,943 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 18:57:56,077 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 18:57:56,078 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 19:00:11,143 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 19:00:11,144 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 19:02:08,606 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 19:02:08,608 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 19:02:08,609 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 19:02:08,610 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 19:02:08,779 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 19:02:08,780 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 19:02:29,558 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 19:02:55,870 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 19:02:55,872 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 19:02:55,940 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 19:02:55,940 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 19:03:16,244 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 19:03:41,484 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 19:03:41,485 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 19:05:17,606 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 19:05:17,607 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 19:05:17,608 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 19:05:17,609 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 19:05:17,728 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 19:05:17,728 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 19:05:38,378 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 19:06:04,116 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 19:06:04,118 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 19:06:04,119 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 19:06:04,120 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 19:06:27,137 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 19:06:52,519 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 19:06:52,520 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 19:06:52,522 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 19:06:52,523 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 19:06:52,585 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 19:06:52,586 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 19:08:24,814 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 19:08:24,816 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 19:08:24,818 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 19:08:24,819 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 19:08:24,884 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 19:08:24,885 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 19:10:05,617 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 19:10:05,619 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 19:10:26,072 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 19:10:51,395 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 19:10:51,396 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 19:12:32,532 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 19:12:32,533 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 19:12:32,589 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 19:12:32,589 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 19:12:52,995 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 19:13:18,304 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 19:13:18,305 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 19:13:18,363 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 19:13:18,364 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 19:14:50,916 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 19:14:50,918 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 19:14:50,920 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 19:14:50,921 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 19:16:26,616 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 19:16:26,617 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 19:17:59,347 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 19:17:59,349 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 19:19:31,876 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 19:19:31,878 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 19:21:14,935 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 19:21:14,936 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 19:21:35,706 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 19:22:04,458 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 19:22:04,460 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 19:22:04,461 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 19:22:04,462 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 19:23:37,084 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 19:23:37,086 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 19:23:37,153 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 19:23:37,154 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 19:23:57,562 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 19:24:22,875 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 19:24:22,876 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 19:24:22,931 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 19:24:22,932 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 19:25:55,232 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 19:25:55,234 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 19:25:55,236 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 19:25:55,237 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 19:25:55,307 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 19:25:55,308 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
