[2025-04-13 15:41:48,881 INFO] [run_gptuner.py:<module>:107] Input arguments: Namespace(config='src/exp_configs/deepseek-v3-overall.yml', folder='default', process='knowledge', db='postgres', database='tpcc_workload', test='tpcc', timeout=180, seed=100, result_path='./experiments_results/deepseek-v3-overall_202504131541', model='deepseek-chat', restart_cmd='sudo docker restart tpcc_workload', recover_script='./scripts/recover_docker_postgres.sh', user='postgres', password='postgres')
[2025-04-13 15:51:53,804 WARNING] [run_gptuner.py:<module>:156] 'checkpoint_segments' is not in postgres
[2025-04-13 16:36:40,038 INFO] [run_gptuner.py:<module>:107] Input arguments: Namespace(config='src/exp_configs/deepseek-v3-overall.yml', folder='deepseek-v3-overall_202504131541', process='knowledge', db='postgres', database='tpcc_workload', test='tpcc', timeout=180, seed=100, result_path='./experiments_results/deepseek-v3-overall_202504131541', model='deepseek-chat', restart_cmd='sudo docker restart tpcc_workload', recover_script='./scripts/recover_docker_postgres.sh', user='postgres', password='postgres')
[2025-04-13 16:36:40,062 WARNING] [run_gptuner.py:<module>:156] 'checkpoint_segments' is not in postgres
