[2025-04-14 23:13:26,007 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:13:26,120 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:13:26,165 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-14 23:13:46,280 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:14:10,258 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:14:10,363 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:14:10,367 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:14:30,569 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:14:54,515 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:14:54,632 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:14:54,635 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:15:14,827 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:15:38,870 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:15:38,983 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:15:38,987 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:15:39,023 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-14 23:15:59,154 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:16:23,312 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:16:23,430 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:16:23,475 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-14 23:16:43,635 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:17:07,700 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:17:07,811 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:18:42,044 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:18:42,160 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:18:42,164 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:19:02,412 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:19:26,357 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:19:26,467 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:19:26,470 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:19:46,635 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:20:10,705 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:20:10,818 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:20:10,861 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-14 23:20:31,038 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:20:55,212 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:20:55,325 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:20:55,367 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-14 23:21:15,541 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:21:39,565 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:21:39,675 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:23:12,596 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:23:12,715 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:23:12,720 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:24:47,376 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:24:47,484 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:24:47,488 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:25:07,691 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:25:31,752 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:25:31,860 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:25:52,008 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:26:16,054 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:26:16,166 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:26:36,321 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:27:00,568 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:27:00,678 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:27:00,682 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:27:20,918 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:27:45,057 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:27:45,172 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:27:45,177 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:28:05,362 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:28:29,474 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:28:29,588 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:28:49,650 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:29:13,633 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:29:13,747 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:29:13,751 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:29:36,469 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:30:00,404 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:30:00,517 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:30:00,559 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-14 23:30:20,755 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:30:44,725 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:30:44,849 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:31:05,063 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:31:29,144 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:31:29,260 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:31:29,264 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:31:49,519 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:32:13,709 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:32:13,834 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:32:13,838 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:32:34,096 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:32:58,187 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:32:58,297 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:32:58,301 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:33:18,526 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:33:42,629 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:33:42,736 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:33:42,740 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:34:02,990 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:34:27,048 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:34:27,155 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:34:27,159 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:34:47,407 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:35:11,416 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:35:11,531 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:35:11,571 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-14 23:36:52,551 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:36:52,665 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:36:52,669 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:37:15,475 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:37:39,505 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:37:39,612 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:37:39,616 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:37:59,835 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:38:23,894 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:38:24,004 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:38:46,210 ERROR] [postgres.py:update_dbms:117] Failed to execute "drop database if exists tpcc_template" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:38:46,210 ERROR] [postgres.py:update_dbms:117] Failed to execute "create database tpcc_template with template benchbase" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:38:46,210 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:40:42,162 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:40:42,273 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:40:42,277 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:40:42,312 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-14 23:42:17,105 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:42:17,228 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:42:17,232 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:42:37,474 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:43:01,584 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:43:01,692 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:43:01,696 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:44:39,493 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:44:39,607 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:44:39,611 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:44:59,848 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:45:23,880 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:45:23,992 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:45:23,996 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:47:03,461 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:47:03,581 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:47:23,807 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:47:47,928 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:47:48,036 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:47:48,040 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:48:08,258 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-14 23:48:32,246 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:48:32,362 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:48:32,365 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:50:09,177 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:50:09,294 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:50:09,298 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:50:09,332 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-14 23:51:43,411 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:51:43,532 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:51:43,536 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:51:43,574 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-14 23:53:17,972 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:53:18,089 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:53:18,093 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:53:18,127 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-14 23:54:49,752 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:54:49,866 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:54:49,870 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:54:49,905 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-14 23:56:21,147 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:56:21,254 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:56:21,258 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:56:21,299 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-14 23:57:56,326 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:57:56,456 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:57:56,461 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:57:56,503 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-14 23:59:26,860 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-14 23:59:26,970 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-14 23:59:26,973 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-14 23:59:47,220 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 00:00:11,284 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:00:11,419 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:00:11,423 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-15 00:00:11,461 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:00:31,684 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 00:00:55,759 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:00:55,882 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:00:55,920 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:01:18,741 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 00:01:42,650 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:01:42,765 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:01:42,806 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:03:17,904 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:03:18,013 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:03:18,053 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:04:53,332 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:04:53,441 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:04:53,445 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-15 00:04:53,476 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:06:24,380 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:06:24,492 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:07:54,894 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:07:54,999 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:07:55,003 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-15 00:07:55,037 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:09:29,643 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:09:29,759 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:09:29,763 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-15 00:09:29,798 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:11:05,598 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:11:05,718 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:12:37,325 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:12:37,428 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:13:00,630 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 00:13:24,629 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:13:24,739 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:13:24,743 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-15 00:13:24,778 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:13:45,030 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 00:14:09,115 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:14:09,229 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:14:09,272 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:14:29,521 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 00:14:53,712 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:14:53,820 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:14:53,824 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-15 00:14:53,859 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:16:25,193 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:16:25,306 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:16:25,311 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-15 00:16:25,352 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:18:00,199 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:18:00,320 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:18:00,358 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:19:33,890 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:19:33,996 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:19:34,034 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:21:08,376 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:21:08,490 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:21:08,529 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:21:31,741 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 00:21:55,716 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:21:55,828 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:23:37,174 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:23:37,299 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:23:37,349 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:25:14,770 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:25:14,975 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:25:14,981 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-15 00:25:15,026 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:25:35,246 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 00:25:59,264 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:25:59,371 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:25:59,410 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:27:34,378 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:27:34,489 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:27:34,532 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:29:09,867 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:29:09,975 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:29:10,014 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:30:45,068 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:30:45,186 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:30:45,230 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:32:20,046 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:32:20,154 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:32:20,194 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:32:43,425 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 00:33:07,529 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:33:07,646 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:33:07,688 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:34:43,043 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:34:43,150 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:34:43,186 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:36:18,390 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:36:18,502 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:36:18,544 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:37:53,363 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:37:53,469 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:38:13,726 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 00:38:37,701 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:38:37,817 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:38:37,857 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:40:13,661 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:40:13,780 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:40:13,822 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:41:48,737 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:41:48,862 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:43:19,684 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:43:19,803 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:43:42,852 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 00:44:07,040 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:44:07,147 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:44:07,184 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:45:38,445 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:45:38,554 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:45:38,596 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:47:13,924 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:47:14,049 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:47:14,095 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:48:49,322 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:48:49,428 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:49:09,735 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 00:49:33,925 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:49:34,040 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:51:09,265 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:51:09,383 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:51:09,388 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-15 00:51:09,424 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:51:29,638 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 00:51:53,772 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:51:53,881 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:51:53,920 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:52:14,171 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 00:52:38,245 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:52:38,361 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:53:01,689 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 00:53:25,800 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:53:25,920 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:53:25,969 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:55:01,810 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:55:01,920 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:55:01,958 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:56:37,079 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:56:37,195 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:56:37,235 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:58:12,086 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:58:12,213 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 00:58:12,253 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 00:59:47,908 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 00:59:48,024 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 01:00:08,353 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 01:00:32,343 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 01:00:32,460 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 01:00:32,504 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 01:00:52,755 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 01:01:16,965 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 01:01:17,079 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 01:01:17,121 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 01:02:52,550 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 01:02:52,658 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 01:02:52,661 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-15 01:03:13,037 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 01:03:37,130 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 01:03:37,250 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 01:03:37,255 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-15 01:03:37,288 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 01:04:00,833 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 01:04:25,235 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 01:04:25,337 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 01:04:25,380 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 01:06:01,075 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 01:06:01,180 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 01:06:01,222 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 01:07:36,570 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 01:07:36,696 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 01:07:56,965 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 01:08:21,180 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 01:08:21,300 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 01:08:21,342 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 01:09:56,439 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 01:09:56,569 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 01:09:56,573 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-15 01:10:16,814 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 01:10:40,918 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 01:10:41,024 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 01:10:41,062 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 01:12:16,096 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 01:12:16,207 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 01:12:16,249 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 01:13:53,929 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 01:13:54,038 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 01:13:54,076 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 01:15:28,854 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 01:15:28,959 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 01:15:28,997 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 01:17:03,390 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 01:17:03,494 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 01:17:03,534 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 01:17:23,836 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 01:17:47,907 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 01:17:48,015 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 01:17:48,018 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-15 01:18:08,295 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 01:18:32,488 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 01:18:32,607 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 01:18:32,650 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 01:18:52,919 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 01:19:16,929 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 01:19:17,043 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 01:19:17,084 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-04-15 01:19:37,402 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 01:20:01,372 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 01:20:01,486 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 01:21:36,248 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 01:21:36,358 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set block_size to '8192';" to update dbms for error: parameter "block_size" cannot be changed

[2025-04-15 01:21:36,361 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_multixact_freeze_max_age to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_multixact_freeze_max_age" (10000 .. 2000000000)

[2025-04-15 01:21:36,393 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

