[2025-05-23 12:05:07,708 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 12:05:07,710 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 12:05:07,711 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:05:07,712 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:05:28,550 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:05:52,938 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 12:05:52,940 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 12:05:52,941 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:05:52,942 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:05:53,001 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:05:53,002 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:06:13,283 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:06:36,595 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:06:36,596 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:06:56,947 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:07:20,209 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:07:20,211 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:07:20,275 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:07:20,276 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:07:40,531 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:08:03,759 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 12:08:03,760 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 12:08:03,761 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:08:03,762 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:08:24,091 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:08:47,519 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:08:47,521 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:08:47,589 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:08:47,590 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:09:07,865 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:09:31,212 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 12:09:31,214 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 12:09:31,215 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:09:31,216 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:09:51,575 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:10:14,848 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:10:14,850 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:11:54,929 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:11:54,931 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:11:54,995 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:11:54,995 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:12:15,242 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:12:38,468 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 12:12:38,470 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 12:12:38,471 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:12:38,472 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:12:38,537 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:12:38,538 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:12:58,847 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:13:22,096 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:13:22,097 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:14:53,916 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 12:14:53,918 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 12:14:53,919 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:14:53,921 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:14:53,994 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:14:53,995 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:16:24,196 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 12:16:24,198 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 12:16:24,200 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:16:24,201 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:16:24,258 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:16:24,258 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:16:44,545 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:17:07,767 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:17:07,768 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:17:28,108 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:17:51,356 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:17:51,357 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:18:11,723 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:18:35,083 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:18:35,084 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:18:35,152 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:18:35,153 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:20:05,466 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 12:20:05,468 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 12:20:05,469 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:20:05,470 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:20:05,535 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:20:05,536 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:20:25,897 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:20:49,154 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 12:20:49,155 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 12:20:49,157 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:20:49,157 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:20:49,216 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:20:49,217 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:21:09,553 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:21:32,840 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 12:21:32,841 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 12:21:32,842 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:21:32,843 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:23:04,955 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:23:04,957 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:23:25,356 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:23:48,649 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:23:48,651 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:23:48,712 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:23:48,713 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:24:08,990 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:24:32,273 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:24:32,274 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:26:05,632 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:26:05,633 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:27:36,613 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:27:36,614 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:27:56,960 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:28:20,294 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:28:20,295 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:28:20,354 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:28:20,354 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:28:40,677 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:29:03,973 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 12:29:03,974 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 12:29:03,975 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:29:03,976 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:29:04,176 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:29:04,177 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:29:24,769 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:29:48,144 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:29:48,145 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:29:48,209 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:29:48,210 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:30:08,541 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:30:31,797 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:30:31,799 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:30:31,860 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:30:31,861 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:32:52,933 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:32:52,935 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:32:52,994 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:32:52,995 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:33:13,319 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:33:36,703 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 12:33:36,704 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 12:33:36,706 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:33:36,707 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:33:59,055 ERROR] [postgres.py:update_dbms:117] Failed to execute "drop database if exists tpcc_template" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:33:59,055 ERROR] [postgres.py:update_dbms:117] Failed to execute "create database tpcc_template with template tpcc_workload" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:33:59,055 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:35:53,020 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:35:53,021 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:37:22,881 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:37:22,882 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:37:22,942 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:37:22,943 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:37:43,290 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:38:06,744 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:38:06,744 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:38:27,039 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:38:50,446 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:38:50,448 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:39:10,832 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:39:34,224 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:39:34,225 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:39:34,288 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:39:34,289 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:39:54,642 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:40:18,053 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:40:18,055 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:40:18,123 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:40:18,124 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:41:48,730 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:41:48,732 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:42:09,045 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:42:32,449 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:42:32,451 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:42:55,695 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:43:19,069 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:43:19,070 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:43:19,140 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:43:19,141 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:43:39,481 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:44:03,171 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:44:03,172 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:45:33,490 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:45:33,492 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:45:33,563 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:45:33,563 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:45:53,912 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:46:17,193 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 12:46:17,195 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 12:46:17,196 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:46:17,197 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:47:55,949 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 12:47:55,951 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 12:47:55,953 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:47:55,954 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:48:16,368 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:48:39,786 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 12:48:39,788 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 12:48:39,790 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:48:39,791 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:49:00,222 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:49:23,642 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 12:49:23,643 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 12:49:23,645 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:49:23,646 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:49:23,717 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:49:23,717 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:49:44,074 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:50:07,397 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:50:07,398 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:50:07,462 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:50:07,463 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:50:27,932 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:50:51,375 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:50:51,377 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:50:51,436 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:50:51,437 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:51:14,594 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 12:51:38,227 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:51:38,229 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:53:08,548 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:53:08,550 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:54:47,467 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:54:47,469 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:57:02,085 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:57:02,087 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 12:57:02,148 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 12:57:02,149 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 12:58:32,627 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 12:58:32,628 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:00:03,116 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:00:03,117 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:01:33,446 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:01:33,447 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:03:12,739 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:03:12,740 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:03:12,805 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 13:03:12,806 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 13:03:37,107 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 13:04:00,478 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:04:00,480 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:04:20,879 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 13:04:44,163 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 13:04:44,165 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 13:04:44,166 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:04:44,167 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:04:44,237 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 13:04:44,237 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 13:05:04,596 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 13:05:28,072 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:05:28,074 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:06:58,365 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:06:58,366 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:08:28,269 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:08:28,271 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:09:58,571 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 13:09:58,572 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 13:09:58,574 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:09:58,575 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:11:29,085 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:11:29,086 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:13:15,899 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:13:15,900 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:14:54,880 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:14:54,881 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:16:34,037 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 13:16:34,038 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 13:16:34,040 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:16:34,041 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:16:34,125 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 13:16:34,126 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 13:16:54,480 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 13:17:17,954 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:17:17,956 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:18:56,515 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:18:56,517 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:20:28,919 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 13:20:28,920 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 13:20:28,922 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:20:28,923 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:21:59,439 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:21:59,440 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:22:19,921 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 13:22:43,289 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 13:22:43,290 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 13:22:43,291 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:22:43,292 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:24:25,765 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:24:25,767 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:25:55,596 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:25:55,597 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:26:15,997 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 13:26:40,044 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:26:40,045 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:28:10,606 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:28:10,607 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:28:10,672 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 13:28:10,673 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 13:28:31,022 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 13:28:54,403 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 13:28:54,404 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 13:28:54,405 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:28:54,406 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:30:25,036 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:30:25,037 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:30:45,461 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 13:31:08,929 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 13:31:08,930 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 13:31:08,931 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:31:08,932 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:32:39,166 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:32:39,167 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:32:39,230 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 13:32:39,230 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 13:33:02,670 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 13:33:25,984 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:33:25,986 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:34:56,729 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:34:56,730 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:36:34,614 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:36:34,616 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:38:04,830 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:38:04,832 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:39:43,601 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:39:43,602 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:41:14,088 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 13:41:14,089 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 13:41:14,090 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:41:14,091 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:41:14,186 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 13:41:14,187 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 13:41:34,606 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 13:41:57,981 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:41:57,983 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:43:32,480 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 13:43:32,481 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 13:43:32,483 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:43:32,484 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:43:56,442 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 13:44:19,913 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 13:44:19,914 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 13:44:19,916 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:44:19,917 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:45:50,803 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:45:50,805 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:47:21,683 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:47:21,684 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:47:21,746 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 13:47:21,746 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 13:48:52,171 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 13:48:52,173 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 13:48:52,174 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:48:52,176 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:48:52,236 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 13:48:52,236 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 13:50:22,946 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 13:50:22,947 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 13:50:22,949 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:50:22,949 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:50:23,009 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 13:50:23,010 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 13:50:43,424 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 13:51:06,810 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:51:06,811 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:51:06,872 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 13:51:06,872 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 13:51:27,190 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 13:51:50,587 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 13:51:50,589 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 13:51:50,590 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:51:50,591 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:53:31,301 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 13:53:31,302 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 13:53:31,303 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:53:31,304 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:53:31,647 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 13:53:31,648 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 13:53:53,188 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 13:54:17,676 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 13:54:17,677 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 13:54:17,679 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:54:17,680 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:54:41,155 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 13:55:04,477 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:55:04,478 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:56:34,774 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:56:34,775 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:58:05,269 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:58:05,270 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 13:58:25,743 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 13:58:49,150 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 13:58:49,152 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 14:00:19,293 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 14:00:19,295 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 14:00:19,357 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 14:00:19,358 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 14:00:39,798 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 14:01:03,129 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 14:01:03,131 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 14:01:03,132 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 14:01:03,133 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 14:02:33,450 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 14:02:33,452 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 14:02:33,453 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 14:02:33,454 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 14:02:56,987 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 14:03:20,380 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 14:03:20,381 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 14:04:51,057 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 14:04:51,059 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 14:06:21,372 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 14:06:21,373 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 14:07:52,442 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 14:07:52,444 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 14:08:12,926 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 14:08:36,488 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 14:08:36,489 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 14:10:06,883 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 14:10:06,884 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 14:10:06,952 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 14:10:06,952 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
[2025-05-23 14:10:27,356 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-05-23 14:10:50,830 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 14:10:50,831 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 14:12:21,515 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set autovacuum_max_workers to '0';" to update dbms for error: 0 is outside the valid range for parameter "autovacuum_max_workers" (1 .. 262143)

[2025-05-23 14:12:21,516 INFO] [postgres.py:set_knob:130] Knob autovacuum_max_workers is set to 3
[2025-05-23 14:12:21,518 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-05-23 14:12:21,519 INFO] [postgres.py:set_knob:130] Knob transaction_isolation is set to read committed
[2025-05-23 14:12:21,596 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-05-23 14:12:21,597 INFO] [postgres.py:set_knob:130] Knob wal_writer_flush_after is set to 1MB
