[2025-04-15 11:59:01,976 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 11:59:02,018 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 11:59:22,205 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 11:59:46,264 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 11:59:46,303 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-15 11:59:46,303 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:01:17,568 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:01:17,611 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:01:17,627 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 12:02:48,724 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:02:48,763 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:02:48,779 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 12:03:08,977 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 12:03:33,193 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:03:33,232 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:03:33,247 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 12:03:53,404 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 12:04:17,543 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:04:17,581 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:04:37,797 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 12:05:01,988 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:05:02,028 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:06:42,769 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:06:42,808 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:07:02,957 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 12:07:27,159 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:07:27,203 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:07:27,222 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 12:07:47,405 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 12:08:11,560 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:08:11,597 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-15 12:08:11,598 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:08:11,620 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 12:08:31,717 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 12:08:55,776 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:08:55,815 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:10:28,246 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:10:28,284 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:11:59,323 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:11:59,364 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:12:19,543 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 12:12:43,637 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:12:43,674 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-15 12:12:43,675 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:14:14,842 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:14:14,883 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:15:45,705 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:15:45,746 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:17:26,469 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:17:26,508 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:18:57,559 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:18:57,599 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:20:29,012 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:20:29,056 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:20:50,692 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 12:21:14,815 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:21:14,861 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:21:35,036 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 12:21:59,187 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:21:59,225 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:23:30,375 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:23:30,412 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:23:50,557 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 12:24:14,694 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:24:14,735 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:25:49,531 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:25:49,569 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:27:29,082 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:27:29,121 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:27:49,365 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 12:28:13,469 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:28:13,509 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:28:13,525 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 12:29:44,269 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:29:44,307 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:30:04,525 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 12:30:28,586 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:30:28,622 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-15 12:30:28,623 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:30:50,036 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 12:31:14,258 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:31:14,298 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:31:14,314 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 12:32:45,406 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:32:45,442 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:32:45,458 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 12:33:07,619 ERROR] [postgres.py:update_dbms:117] Failed to execute "drop database if exists tpcc_template" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 12:33:07,619 ERROR] [postgres.py:update_dbms:117] Failed to execute "create database tpcc_template with template benchbase" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 12:33:07,620 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 12:35:01,377 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:35:01,414 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:36:35,509 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:36:35,545 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-15 12:36:35,545 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:38:06,426 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:38:06,466 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:38:26,680 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 12:38:50,721 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:38:50,762 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:40:22,147 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:40:22,189 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-15 12:40:22,190 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:41:54,550 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:41:54,590 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:42:14,790 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 12:42:39,068 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:42:39,182 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-15 12:42:39,182 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:44:10,993 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:44:11,039 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:44:33,062 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 12:44:57,245 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:44:57,283 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-15 12:44:57,283 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:46:31,424 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:46:31,461 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:48:05,586 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:48:05,627 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:49:36,341 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:49:36,383 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:51:06,795 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:51:06,835 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:52:37,681 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:52:37,722 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:54:08,756 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:54:08,795 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:54:08,809 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 12:55:40,714 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:55:40,753 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:56:01,032 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 12:56:25,529 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:56:25,569 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-15 12:56:25,570 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:56:47,725 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 12:57:11,709 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:57:11,750 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:57:11,766 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 12:58:47,378 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 12:58:47,414 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 12:58:47,431 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:00:18,108 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:00:18,148 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:00:18,165 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:01:51,971 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:01:52,006 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-15 13:01:52,007 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:01:52,022 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:02:12,180 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 13:02:36,142 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:02:36,178 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:02:36,192 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:04:07,757 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:04:07,797 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:04:07,813 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:04:28,037 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 13:04:52,088 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:04:52,129 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:04:52,146 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:06:25,829 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:06:25,866 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:06:25,883 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:06:48,277 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 13:07:12,464 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:07:12,509 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:08:44,554 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:08:44,591 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:08:44,608 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:09:04,837 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 13:09:28,986 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:09:29,024 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-15 13:09:29,024 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:11:00,994 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:11:01,037 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:12:40,374 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:12:40,497 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:12:40,545 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:14:12,567 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:14:12,606 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:15:47,823 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:15:47,865 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:17:25,178 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:17:25,215 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:17:25,230 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:18:57,482 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:18:57,525 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-15 13:18:57,526 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:18:57,544 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:19:17,736 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 13:19:41,740 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:19:41,781 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:20:02,036 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 13:20:25,869 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:20:25,905 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-15 13:20:25,906 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:20:25,923 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:22:00,593 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:22:00,631 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-15 13:22:00,632 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:22:00,648 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:23:32,845 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:23:32,886 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:23:32,904 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:25:08,327 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:25:08,364 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-15 13:25:08,365 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:25:08,381 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:26:40,699 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:26:40,734 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-15 13:26:40,735 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:26:40,750 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:28:13,844 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:28:13,880 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:28:13,898 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:28:34,120 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 13:28:58,141 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:28:58,182 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:28:58,198 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:30:33,081 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:30:33,120 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:30:33,138 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:32:04,788 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:32:04,824 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:32:25,032 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 13:32:49,351 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:32:49,391 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:32:49,408 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:33:09,645 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 13:33:33,815 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:33:33,856 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:33:33,874 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:33:54,076 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 13:34:18,098 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:34:18,141 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:34:18,159 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:35:49,651 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:35:49,690 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:35:49,707 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:37:23,141 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:37:23,181 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:37:43,427 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 13:38:08,412 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:38:08,455 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:39:39,635 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:39:39,675 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:41:11,310 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:41:11,350 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:42:43,687 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:42:43,730 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:43:03,958 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 13:43:27,949 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:43:27,990 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:43:48,236 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 13:44:12,438 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:44:12,483 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:44:32,672 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 13:44:56,848 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:44:56,890 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:44:56,907 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:45:18,939 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 13:45:43,080 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:45:43,119 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-15 13:45:43,120 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:47:14,654 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:47:14,691 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-15 13:47:14,692 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:48:46,343 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:48:46,376 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-15 13:48:46,377 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:50:17,922 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:50:17,960 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:51:49,768 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:51:49,808 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:51:49,826 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:52:10,075 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 13:52:34,062 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:52:34,102 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:52:34,118 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:52:54,368 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 13:53:18,663 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:53:18,703 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-15 13:53:18,703 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:53:18,719 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:54:50,473 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:54:50,515 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:54:50,531 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 13:55:10,860 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 13:55:34,856 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:55:34,895 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:55:57,039 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 13:56:21,903 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:56:21,946 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:57:53,561 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:57:53,601 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:59:24,775 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 13:59:24,815 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 13:59:45,073 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 14:00:09,207 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 14:00:09,250 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 14:01:40,889 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 14:01:40,929 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 14:02:01,193 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 14:02:25,167 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 14:02:25,209 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 14:03:57,085 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 14:03:57,123 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 14:04:19,440 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 14:04:43,533 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 14:04:43,574 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 14:06:15,491 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 14:06:15,531 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 14:07:47,188 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 14:07:47,230 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 14:09:19,566 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 14:09:19,603 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 14:09:19,618 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 14:09:39,866 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system reset all;" to update dbms for error: 'NoneType' object has no attribute 'autocommit'
[2025-04-15 14:10:03,951 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 14:10:03,989 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-15 14:10:03,990 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'repeatable read';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 14:11:35,800 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 14:11:35,835 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set statement_timeout to '-1';" to update dbms for error: -1 ms is outside the valid range for parameter "statement_timeout" (0 .. 2147483647)

[2025-04-15 14:11:35,835 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read uncommitted';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 14:11:35,851 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

[2025-04-15 14:13:08,780 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'on';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 14:13:08,820 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'serializable';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 14:14:40,138 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set in_hot_standby to 'off';" to update dbms for error: unrecognized configuration parameter "in_hot_standby"

[2025-04-15 14:14:40,180 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set transaction_isolation to 'read committed';" to update dbms for error: parameter "transaction_isolation" cannot be changed

[2025-04-15 14:14:40,196 ERROR] [postgres.py:update_dbms:117] Failed to execute "alter system set wal_writer_flush_after to '-1';" to update dbms for error: -1 8kB is outside the valid range for parameter "wal_writer_flush_after" (0 .. 2147483647)

